export const SUPERHEROES_FETCH = 'SUPERHEROES_FETCH';
export const SUPERHEROES_FETCH_START = 'SUPERHEROES_FETCH_START';
export const SUPERHEROES_FETCH_FAILED = 'SUPERHEROES_FETCH_FAILED';
export const SUPERHEROES_FETCH_SUCCESS = 'SUPERHEROES_FETCH_SUCCESS';